// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIRPDn9fApZs0j7I0LCJmwwjIxKdTJM0',
    appId: '1:563840548008:web:88581982d674df8440969d',
    messagingSenderId: '563840548008',
    projectId: 'frostnews-ed366',
    authDomain: 'frostnews-ed366.firebaseapp.com',
    storageBucket: 'frostnews-ed366.firebasestorage.app',
    measurementId: 'G-LV4LKHCLMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBShwpQCSDm7A9CIicoSsSRMrnzDCTy79c',
    appId: '1:563840548008:android:32dae49a986b50bf40969d',
    messagingSenderId: '563840548008',
    projectId: 'frostnews-ed366',
    storageBucket: 'frostnews-ed366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiLw67iZt-N4X2rsLusCiPZ1ght6er40',
    appId: '1:563840548008:ios:ff0771deeace173640969d',
    messagingSenderId: '563840548008',
    projectId: 'frostnews-ed366',
    storageBucket: 'frostnews-ed366.firebasestorage.app',
    iosBundleId: 'com.example.tbKelompok1b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNiLw67iZt-N4X2rsLusCiPZ1ght6er40',
    appId: '1:563840548008:ios:ff0771deeace173640969d',
    messagingSenderId: '563840548008',
    projectId: 'frostnews-ed366',
    storageBucket: 'frostnews-ed366.firebasestorage.app',
    iosBundleId: 'com.example.tbKelompok1b',
  );
}
